http:
  routers:
    freescout_http:
      rule: "Host(`{{ freescout_url }}`)"
      service: "freescout-app@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    freescout_https:
      rule: "Host(`{{ freescout_url }}`)"
      service: "freescout-app@file"
      entryPoints:
        - "https"
      middlewares:
        - "removeAuthHeaders"
      tls:
        certResolver: "le_http"
  services:
    freescout-app:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ freescout_louketo_port }}"
  middlewares:
    removeAuthHeaders:
      headers:
        customRequestHeaders:
          X-Auth-Email: ""
          X-Auth-Audience: ""
          X-Auth-ExpiresIn: ""
          X-Auth-Groups: ""
          X-Auth-Roles: ""
          X-Auth-Subject: ""
          X-Auth-Token: ""
          X-Auth-UserID: ""
          X-Auth-Username: ""
