http:
  routers:
    keycloak-http:
      rule: "Host(`sso.{{ base_url }}`)"
      service: "keycloak@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    keycloak-https:
      rule: "Host(`sso.{{ base_url }}`)"
      service: "keycloak@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
  services:
    keycloak:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ keycloak_http_port }}"
