http:
  routers:
    mumble-web_http:
      rule: "Host(`mumble.{{ base_url }}`)"
      service: "mumble-web-app@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    mumble-web_https:
      rule: "Host(`mumble.{{ base_url }}`)"
      service: "mumble-web-app@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
        domains:
          - main: "mumble.{{ base_url }}"
            sans:
              - "{{ base_url }}"
  services:
    mumble-web-app:
      loadBalancer:
        servers:
          - url: "http://{{ ansible_fqdn }}:{{ mumble_web_listen }}"
