http:
  routers:
    pretix_http:
      rule: "Host(`pretix.{{ base_url }}`)"
      service: "pretix-app@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    pretix_https:
      rule: "Host(`pretix.{{ base_url }}`)"
      service: "pretix-app@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
  services:
    pretix-app:
      loadBalancer:
        servers:
          - url: "http://{{ pretix_bind_address }}"
