---
# Fix for Debian Buster: https://github.com/docker/docker-py/issues/1502#issuecomment-509898861
- name: Install python3-zeroc-ice
  apt:
    name: python3-zeroc-ice
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Install python3-mastodon
  apt:
    name: python3-mastodon
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: copy script
  template:
    src: users_in_channel.py.j2
    dest: /usr/local/bin/users_in_channel.py.j2
    mode: u=rwx,g=rx,o=rx

- name: copy systemd service file
  copy:
    dest: /etc/systemd/system/users_in_channel.service
    src: users_in_channel.service

- name: start and enable service
  service:
    name: users_in_channel.service
    state: started
    enabled: true
