---
dokuwiki_title: "{{ base_url }} Wiki"
dokuwiki_basedir: /var/www/dokuwiki
dokuwiki_plugins:
  - tag
  - pagelist
  - smtp
  - sqlite
  - nspages
  - move
  - icalevents
  - legalnotice
  - name: "oauth"
    source: https://github.com/wintamute/dokuwiki-plugin-oauth
    source_type: git
  - name: popularity
    state: absent
  - name: authad
    state: absent
  - name: authldap
    state: absent
  - name: authmysql
    state: absent
  - name: authpdo
    state: absent
  - name: authpgsql
    state: absent

dokuwiki_source: tar
dokuwiki_source_tar: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-2020-07-29.tgz
dokuwiki_user: www-data
dokuwiki_acl_all: 1
dokuwiki_acl_user: 8
dokuwiki_language: de-informal
dokuwiki_additonal_configuration:
  - name: userewrite
    value: 1
  - name: subscribers
    value: 1
  - name: useslash
    value: 1
  - name: "authtype"
    value: "'oauth'"
  - name: "disableactions"
    value: "'register'"
  - name: mailfrom
    value: "'wiki@{{ mail_base_domain }}'"
  - name: "plugin>smtp>smtp_host"
    value: "'{{ lookup('passwordstore', 'infra/mail subkey=url') }}'"
  - name: "plugin>smtp>smtp_port"
    value: 465
  - name: "plugin>smtp>smtp_ssl"
    value: "'ssl'"
  - name: "plugin>smtp>auth_user"
    value: "'{{ lookup('passwordstore', 'infra/mail subkey=user') }}'"
  - name: "plugin>smtp>auth_pass"
    value: "'{{ lookup('passwordstore', 'infra/mail') }}'"
  - name: "plugin>smtp>localdomain"
    value: "'{{ mail_base_domain }}'"
  - name: "plugin>tag>toolbar_icon"
    value: 1
  - name: "plugin>icalevents>locationUrlPrefix"
    value: "''"
  - name: "plugin>icalevents>template:default"
    value: "'=== {date}: {summary} ===\n**Location**: {location_link}\n{description}'"
  - name: "plugin>icalevents>template:list"
    value: "'=== {date}: {summary} ===\n**<sup>Location: {location}</sup>**\n{description}'"
  - name: "plugin>icalevents>template:custom1"
    value: "'=== {date}: {summary} ===\n{description}\n**Wo?**: {location_link}'"
  - name: "plugin>oauth>keycloak-key"
    value: "'wiki'"
  - name: "plugin>oauth>keycloak-authurl"
    value: "'{{ sso_base_url }}/protocol/openid-connect/auth'"
  - name: "plugin>oauth>keycloak-tokenurl"
    value: "'{{ sso_base_url }}/protocol/openid-connect/token'"
  - name: "plugin>oauth>keycloak-userinfourl"
    value: "'{{ sso_base_url }}/protocol/openid-connect/userinfo'"
  - name: "plugin>oauth>register-on-auth"
    value: "1"
  - name: "plugin>legalnotice>text"
    value: |
      'Ab dem 21.10.2020 ist der Login nur noch über Keycloak möglich. Bis dahin müssen alle bestehenden Accounts umgezogen werden.
  
      Erstellt euch dafür einen Account auf [[https://sso.chaos.jetzt]], meldet euch mit euren alten Zugangsdaten hier an, navigiert in euer **Benutzerprofil** und aktiviert unter **Mit anderen Services anmelden:** Keycloak. Ab dann könnt ihr euch mit Keycloak anmelden.'
#  - name: "plugin>oauth>singleService"
#    value: "'Keycloak'"

dokuwiki_addional_acronyms:
  - short: CCC
    long: Chaos Computer Club e.V.
