---
freescout_url: "support.{{ base_url }}"
freescout_db_database: "freescout"
freescout_db_username: "{{ lookup('passwordstore', 'infra/freescout/db subkey=user') }}"
freescout_db_password: "{{ lookup('passwordstore', 'infra/freescout/db') }}"

freescout_admin_user:
  email: info@chaos.jetzt
  firstName: Chaos
  lastName: Jetzt
  password: "{{ lookup('passwordstore', 'infra/freescout/admin') }}"

freescout_nginx_port: 89
freescout_louketo_port: 8089

freescout_basedir: /var/www/freescout
freescout_source: git
freescout_source_git_version: 1.7.15
freescout_user: www-data
freescout_config:
  - name: app_url
    value: "https://{{ freescout_url }}"
  - name: app_force_https
    value: "true"
  - name: db_connection
    value: pgsql
  - name: db_host
    value: localhost
  - name: db_port
    value: 5432
  - name: db_database
    value: "{{ freescout_db_database }}"
  - name: db_username
    value: "{{ freescout_db_username }}"
  - name: db_password
    value: "{{ freescout_db_password }}"

