keycloak_postgresql_username: "{{ lookup('passwordstore', 'infra/keycloak/db subkey=user') }}"
keycloak_postgresql_password: "{{ lookup('passwordstore', 'infra/keycloak/db') }}"
keycloak_postgresql_database: "keycloak"

keycloak_configure_firewall: false
keycloak_external_url: "sso.{{ base_url }}"
keycloak_bind_address: 127.0.0.1
keycloak_http_port: 8081
keycloak_welcome_theme: "cj-keycloak-theme"
keycloak_profile_preview: true
keycloak_version: 12.0.0

keycloak_admin_password: "{{ lookup('passwordstore', 'infra/keycloak/admin') }}"

keycloak_registration_captcha_version: "1.1.0"
keycloak_registration_captcha_url: "https://github.com/chaos-jetzt/keycloak-registration-captcha/releases/download/v{{ keycloak_registration_captcha_version }}/registration-captcha.jar"
