---
louketo_instances:
  - name: freescout
    config: |
      client-id: freescout
      discovery-url: https://sso.chaos.jetzt/auth/realms/chaos-jetzt
      enable-default-deny: false
      listen: 127.0.0.1:{{ freescout_louketo_port }}
      upstream-url: http://localhost:{{ freescout_nginx_port }}
      resources:
        - uri: /login*
    state: present
