---
# Synapse
synapse_database_host: "localhost"
synapse_database_database: "synapse"
synapse_database_user: "synapse"
synapse_database_password: "{{ lookup('passwordstore', 'infra/matrix/db create=true') }}"
synapse_registration_shared_secret: "{{ lookup('passwordstore', 'infra/matrix/registration') }}"
synapse_macaroon_secret_key: "{{ lookup('passwordstore', 'infra/matrix/macaroon') }}"
synapse_form_secret: "{{ lookup('passwordstore', 'infra/matrix/form') }}"
synapse_signing_key: "{{ lookup('passwordstore', 'infra/matrix/signing') }}"
synapse_allow_public_rooms_over_federation: true
synapse_enable_group_creation: true
synapse_enable_registration: true
synapse_domain: "{{ base_url }}"
synapse_server_fqdn_matrix: "matrix.{{ synapse_domain }}"
synapse_pip_version: "1.21.2"
synapse_auto_join_rooms:
  - "#grosse_halle:{{ base_url }}"
  - "#allgemein:{{ base_url }}"
synapse_email_enabled: true
synapse_email_smtp_host: "{{ lookup('passwordstore', 'infra/mail subkey=url') }}"
synapse_email_smtp_port: 587
synapse_email_smtp_user: "{{ lookup('passwordstore', 'infra/mail subkey=user') }}"
synapse_email_smtp_password: "{{ lookup('passwordstore', 'infra/mail') }}"
synapse_email_smtp_require_transport_security: no
synapse_email_client_base_url: "https://chat.{{ base_url }}"

synapse_http_listener_port: '85'
synapse_federation_listener_port: '86'

synapse_app_service_config_files:
  - /etc/matrix-appservice-irc/appservice-registration-irc.yaml

synapse_turn_uris:
  - "turn:{{ coturn_realm }}:3479?transport=udp"
  - "turn:{{ coturn_realm }}:3479?transport=tcp"

synapse_turn_shared_secret: "{{ coturn_static_auth_secret }}"
synapse_turn_allow_guests: True

# Riot
riot_installation_path: "/var/www/riot-web"
riot_version: "1.7.9"

# Matrix-Appservice-IRC
irc_hs_token: "{{ lookup('passwordstore', 'infra/irc-bridge subkey=hs_token') }}"
irc_as_token: "{{ lookup('passwordstore', 'infra/irc-bridge subkey=as_token') }}"

# Maubot
maubot_unshared_secret: "{{ lookup('passwordstore', 'infra/maubot/unshared') }}"
maubot_admin_password: "{{ lookup('passwordstore', 'infra/maubot/admin') }}"
