---
# Synapse
synapse_database_host: "localhost"
synapse_database_database: "synapse"
synapse_database_user: "synapse"
synapse_database_password: "{{ lookup('passwordstore', 'infra/matrix/db create=true') }}"
synapse_registration_shared_secret: "{{ lookup('passwordstore', 'infra/matrix/registration') }}"
synapse_macaroon_secret_key: "{{ lookup('passwordstore', 'infra/matrix/macaroon') }}"
synapse_form_secret: "{{ lookup('passwordstore', 'infra/matrix/form') }}"
synapse_signing_key: "{{ lookup('passwordstore', 'infra/matrix/signing') }}"
synapse_allow_public_rooms_over_federation: true
synapse_enable_group_creation: true
synapse_domain: "{{ base_url }}"
synapse_server_fqdn_matrix: "matrix.{{ synapse_domain }}"
synapse_pip_version: "1.75.0"
synapse_pip_packages_additional:
  - "git+https://github.com/chaos-jetzt/matrix-synapse-saml-mapper"
synapse_auto_join_rooms:
  - "#grosse_halle:{{ base_url }}"
  - "#allgemein:{{ base_url }}"
synapse_email_enabled: true
synapse_email_smtp_host: "{{ lookup('passwordstore', 'infra/mail subkey=url') }}"
synapse_email_smtp_port: 587
synapse_email_smtp_user: "{{ lookup('passwordstore', 'infra/mail subkey=user') }}"
synapse_email_smtp_password: "{{ lookup('passwordstore', 'infra/mail') }}"
synapse_email_smtp_require_transport_security: no
synapse_email_client_base_url: "https://chat.{{ base_url }}"
synapse_password_config_enabled: false
synapse_enable_registration: false

synapse_http_listener_port: '85'
synapse_http_listener_enabled: false
synapse_federation_listener_enabled: false
synapse_metrics_enabled: false
synapse_additional_listeners: |
  # Unsecure HTTP listener (Client API): for when matrix traffic passes through a reverse proxy
  # that unwraps TLS.
  - port: {{ synapse_http_listener_port }}
    tls: false
    bind_addresses: ['::1', '127.0.0.1']
    type: http
    x_forwarded: true
    resources:
      - names: [client,federation]
        compress: false
    additional_resources:
      "/_matrix/saml2/pick_username":
        module: "matrix_synapse_saml_mapper.pick_username_resource"


synapse_app_service_config_files:
  - /etc/matrix-appservice-irc/appservice-registration-irc.yaml

synapse_turn_uris:
  - "turn:{{ coturn_realm }}:3479?transport=udp"
  - "turn:{{ coturn_realm }}:3479?transport=tcp"

synapse_turn_shared_secret: "{{ coturn_static_auth_secret }}"
synapse_turn_allow_guests: True

synapse_homeserver_config_extra_options: |
  user_directory:
    enabled: true
    search_all_users: true
  saml2_config:
    enabled: true
    sp_config:
      metadata:
        remote:
          - url: {{ sso_base_url }}/protocol/saml/descriptor
    user_mapping_provider:
      module: "matrix_synapse_saml_mapper.SamlMappingProvider"
  sso:
    client_whitelist:
      - "https://chat.{{ base_url }}/"

# Element Web
element_web_installation_path: "/var/www/riot-web"
element_web_version: "1.11.20"

# Matrix-Appservice-IRC
irc_hs_token: "{{ lookup('passwordstore', 'infra/irc-bridge subkey=hs_token') }}"
irc_as_token: "{{ lookup('passwordstore', 'infra/irc-bridge subkey=as_token') }}"

# Maubot
maubot_unshared_secret: "{{ lookup('passwordstore', 'infra/maubot/unshared') }}"
maubot_admin_password: "{{ lookup('passwordstore', 'infra/maubot/admin') }}"


synapse_dependencies:
  - build-essential
  - python3-dev
  - libffi-dev
  - python3-pip
  - python3-wheel
  - python3-setuptools
  - python3-virtualenv
  - python3-venv
  - sqlite3
  - libssl-dev
  - libjpeg-dev
  - libxslt1-dev
  - libpq-dev
  - libxslt1-dev
  - xmlsec1
  - python3-icu
