---
mumble_domain: "mumble.{{ base_url }}"
murmur_icesecretread: "secret"
murmur_welcometext: "Welcome on the {{ base_url }}-mumble server running murmur. Enjoy your stay!"
murmur_bandwidth: "128000"
murmur_sslcert: "/etc/ssl/certs/{{ mumble_domain }}.crt"
murmur_sslkey: "/etc/ssl/private/{{ mumble_domain }}.key"
murmur_registername: false
murmur_registry_password: "{{ lookup('passwordstore', 'infra/murmur/registry create=true') }}"

mumble_web: true
mumble_web_path: "/usr/lib/node_modules/mumble-web"
mumble_web_config: ""
mumble_web_supplementary_groups: "ssl-cert"
mumble_web_listen: "127.0.0.1:84"
mumble_web_ssl_activated: false
mumble_web_ssl_target: true
