nodejs_install_npm_user: "root"
murmur_icesecretread: "secret"
murmur_welcometext: "Welcome on the {{ base_url }}-mumble server running murmur. Enjoy your stay!"
murmur_bandwidth: "128000"
murmur_sslcert: "/etc/ssl/certs/mumble.{{ base_url }}.crt"
murmur_sslkey: "/etc/ssl/private/mumble.{{ base_url }}.key"
murmur_registername: no
murmur_registry_password: "{{ lookup('passwordstore', 'infra/murmur/registry create=true') }}"

mumble_web: yes
mumble_web_path: "/usr/lib/node_modules/mumble-web"
mumble_web_config: ""
mumble_web_supplementary_groups: "ssl-cert"
mumble_web_listen: "84"
mumble_web_ssl_activated: False
mumble_web_ssl_target: True
