---
nginx_remove_default_vhost: true
nginx_user: www-data
nginx_vhosts_paths: "[{% for group in groups %}'../templates/nginx/{{ group }}',{% endfor %}]"
nginx_vhosts: "[{% for path in nginx_vhosts_paths %}{% for file in lookup('fileglob', path + '/*', wantlist=True) %}{ 'server_name': '_', 'filename': '{{ file.split('/')[-1].replace('.j2', '') }}', 'template': '{{ file }}' },{% endfor %}{% endfor %}]"
