---
postgresql_python_library: python3-psycopg2
postgresql_users:
  - name: "{{ pretix_database_user }}"
    password: "{{ lookup('passwordstore', 'infra/pretix/db') }}"
  - name: "{{ synapse_database_user }}"
    password: "{{ synapse_database_password }}"
  - name: "{{ keycloak_postgresql_username }}"
    password: "{{ keycloak_postgresql_password }}"
  - name: "{{ freescout_db_username }}"
    password: "{{ freescout_db_password }}"
postgresql_databases:
  - name: "{{ pretix_database_name }}"
    owner: "{{ pretix_database_user }}"
  - name: "{{ synapse_database_database }}"
    owner: "{{ synapse_database_user }}"
    lc_collate: 'C'
    lc_ctype: 'C'
  - name: "{{ keycloak_postgresql_database }}"
    owner: "{{ keycloak_postgresql_username }}"
  - name: "{{ freescout_db_database }}"
    owner: "{{ freescout_db_username }}"
