---
- name: install firewalld
  package:
    name: firewalld
    state: present

- firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes

- firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- firewalld:
    service: https
    permanent: yes
    state: enabled
    immediate: yes

- firewalld:
    port: 64738/tcp
    permanent: yes
    state: enabled
    immediate: yes

- firewalld:
    port: 64738/udp
    permanent: yes
    state: enabled
    immediate: yes

- firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes

- firewalld:
    port: 8181/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Enable firewalld on system reboot
     service: name=firewalld enabled=yes state=started
