---
- name: delete old traefik config file
  file:
    path: '/root/traefik/traefik.toml'
    state: absent

- name: make sure config-directories exist
  file:
    path: '/root/{{ item }}'
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0755
  with_items:
  - matrix-appservice-irc/
  - murmur/
  - nginx/html_known/.well-known/matrix/
  - pretix/
  - riot/
  - synapse/
  - maubot/

- name: change owner of synapse media-directories
  file:
    path: '/root/{{ item }}'
    state: directory
    recurse: yes
    owner: '991'
    group: '991'
    mode: 0755
  with_items:
  - synapse/media_store/
  - synapse/uploads/

- name: mass-copy config files
  template:
    dest: '/root/{{ item }}'
    src: '{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
  - matrix-appservice-irc/appservice-registration-irc.yaml
  - matrix-appservice-irc/config.yaml
  - murmur/murmur.ini
  - nginx/default.conf
  - nginx/html_known/.well-known/matrix/server
  - pretix/pretix.cfg
  - riot/config.json
  - synapse/homeserver.yaml
  - synapse/synapse.log.config
  - synapse/synapse.signing.key
  - maubot/config.yaml

- name: clone website repo
  git:
    repo: 'https://github.com/chaos-jetzt/jetztstatic/'
    dest: /root/nginx/html
    clone: yes
    update: yes
