---
- name: delete old traefik config file
  file:
    path: '/root/traefik/traefik.toml'
    state: absent

- name: make sure config-directories exist
  file:
    path: '/root/{{ item }}'
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0755
  with_items:
  - matrix-appservice-irc/
  - riot/
  - maubot/


- name: mass-copy config files
  template:
    dest: '/root/{{ item }}'
    src: '{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
  - matrix-appservice-irc/appservice-registration-irc.yaml
  - matrix-appservice-irc/config.yaml
  - riot/config.json

