---
- name: Create the web network
  docker_network:
    name: web

- include: files.yml

- include: compose.yml

- name: setup traefik certificate-exporter cronjob
  cron:
    name: traefik certificate-exporter
    hour: "2"
    user: root
    job: '/root/traefik/dumpcerts.sh /root/traefik/letsencrypt/acme_http.json /etc/ssl/'

- name: run traefik certificate-exporter
  shell:
    cmd: '/root/traefik/dumpcerts.sh /root/traefik/letsencrypt/acme_http.json /etc/ssl/'
  become: true
