---
- name: check if old website is still present
  lineinfile:
    path: '{{ website_path }}/.git/config'
    regexp: 'url = https://github\.com/chaos-jetzt/jetztstatic'
    state: absent
  check_mode: yes
  register: website_old_present


- name: delete old website if present
  file:
    state: absent
    path: '{{ website_path }}'
  when: website_old_present.found

- name: clone website repository
  git:
    repo: '{{ website_repo }}'
    dest: '{{ website_path }}'
    version: 'master'
    clone: yes
    update: yes
  register: website_changed

- name: install pip requirements for website
  pip:
    requirements: '{{ website_path }}/requirements.txt'

- name: make html on website
  make:
    target: html
    chdir: '{{ website_path }}'
  when: website_changed

- name: Ensure well-known matrix dir exists
  file:
    path: /var/www/.well-known/matrix/
    state: directory

- name: copy matrix discovery file
  template:
    src: matrix/server.j2
    dest: /var/www/.well-known/matrix/server
