---
- name: clone website repository
  git:
    repo: 'https://github.com/chaos-jetzt/jetztstatic/'
    dest: /var/www/website
    clone: yes
    update: yes

- name: Ensure well-known matrix dir exists
  file:
    path: /var/www/.well-known/matrix/
    state: directory

- name: copy matrix discovery files
  template:
    src: "matrix/{{ item }}.j2"
    dest: "/var/www/.well-known/matrix/{{ item }}"
  loop:
    - server
    - client
