---
- name: install firewalld
  package:
    name: firewalld
    state: present

- firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes
#this is seperate so you don't accidentally remove it

- firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - ssh
    - http
    - https
    - murmur

- firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 8080/tcp 
    - 8181/tcp
    - 8008/tcp
    - 8090/tcp
    - 8448/tcp

- name: Enable firewalld on system reboot
  service:
    name: firewalld
    enabled: yes
    state: started
