---
- name: install firewalld
  package:
    name: firewalld
    state: present

- name: Open SSH-Port in firewall
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes
#this is seperate so you don't accidentally remove it

- name: Open services in firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items: "{{ firewall_services }}"

- name: Open ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items: "{{ firewall_ports }}"

- name: Enable firewalld on system reboot
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Add docker ips to trusted zone
  firewalld:
    source: 172.17.0.0/16
    zone: trusted
    permanent: yes
    state: enabled
  notify: reload firewalld
