providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

certificatesResolvers:
  le_http:
    acme:
      httpChallenge:
        entryPoint: http
      email: mail@{{ base_url }}
      storage: /etc/traefik/letsencrypt/acme.json

log:
  format: json
  level: INFO
