---
- name: Ensure traefik docker-container exists
  docker_container:
    name: traefik
    image: traefik:2.1
    command: --providers.docker
    restart_policy: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik:/etc/traefik/
      - /etc/traefik/letsencrypt:/letsencrypt
    state: stopped