---
- hosts: all
  roles:
    - base
    - jnv.unattended-upgrades
    - em0lar.oh-my-zsh
  handlers:
    - name: restart systemd-journald
      systemd:
        name: systemd-journald.service
        state: restarted
  tasks:
    - name: Change SystemMaxUse in systemd-journald
      replace:
        path: "/etc/systemd/journald.conf"
        regexp: "^#SystemMaxUse="
        replace: "SystemMaxUse=50M"
      notify: restart systemd-journald
  tags: base

- hosts: web
  roles:
    - firewalld
  tags: firewall

- hosts: web
  roles:
    - em0lar.traefik
  tasks:
    - name: Create ssl-cert group
      group:
        name: "ssl-cert"
        system: yes

    - name: Make private cert folder readable for ssl-cert group
      file:
        path: "/etc/ssl/private"
        group: "ssl-cert"
        mode: "0750"
        state: directory

    - name: copy certificate export script
      template:
        dest: "{{ traefik_config_directory }}/dumpcerts.sh"
        src: "../templates/traefik/dumpcerts.sh"
        owner: "root"
        group: "root"
        mode: 0744

    - name: setup traefik certificate-exporter cronjob
      cron:
        name: "traefik certificate-exporter"
        minute: "1"
        hour: "2"
        user: "root"
        job: "{{ traefik_config_directory }}/dumpcerts.sh {{ traefik_config_directory }}/acme.json /etc/ssl/"

    - name: run traefik certificate-exporter
      command: '{{ traefik_config_directory }}/dumpcerts.sh {{ traefik_config_directory }}/acme.json /etc/ssl/'
      become: true
      ignore_errors: yes
  tags:
    - traefik

- hosts: web
  roles:
    - geerlingguy.postgresql
  tags: pretix,matrix,keycloak


- hosts: web
  roles:
    - geerlingguy.java
    - em0lar.keycloak
    - mrlesmithjr.openldap
  tags: keycloak

- hosts: web
  roles:
    - docker
    - matrix-appservice-irc
  tags:
    - matrix

- hosts: web
  pre_tasks:
    - name: add php repository
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present
  roles:
    - geerlingguy.nginx
    - geerlingguy.php
    - n0emis.dokuwiki
  tags: wiki

- hosts: web
  roles:
    - geerlingguy.nginx
    - website
  tags: website

- hosts: web
  roles:
    - n0emis.synapse
  tags: matrix

- hosts: web
  roles:
    - maubot
  tags: matrix, maubot

- hosts: web
  roles:
    - geerlingguy.nginx
    - riot-web
  tags: matrix,riot

- hosts: web
  tasks:
    - name: create password-user
      user:
        name: "pass"
        state: present

    - name: "add user to pass's authorized_keys"
      authorized_key:
        user: "pass"
        manage_dir: true
        key: "{{ item.public_key }}"
        state: present
      with_items:
        - "{{ users + password_users }}"
      when: item.state != 'absent' and item.public_key is defined and item.public_key != ''

    - name: "remove user from pass's authorized_keys"
      authorized_key:
        user: "pass"
        manage_dir: true
        key: "{{ item.public_key }}"
        state: absent
      with_items:
        - "{{ users + password_users }}"
      when: item.state == 'absent' and item.public_key is defined and item.public_key != ''
  tags: password_store

- hosts: web
  roles:
    - geerlingguy.redis
    - em0lar.pretix
  tags: pretix

- hosts: web
  pre_tasks:
    - name: add mumble repository
      apt_repository:
        repo: "ppa:mumble/release"
        state: present
  roles:
    - geerlingguy.nodejs
    - systemli.mumble
  tasks:
    - name: Make database readable by mumble group
      file:
        path: "{{ murmur_database }}"
        owner: "mumble-server"
        group: "mumble-server"
        mode: "0660"
      notify:
        - restart murmur

    - name: Make mumble certificate readable by ssl-cert group
      file:
        path: "{{ murmur_sslkey }}"
        group: "ssl-cert"
        mode: "0640"
      notify:
        - restart murmur
        - restart mumble-web

    - name: Add user mumble-server to ssl-cert group
      user:
        name: "mumble-server"
        groups: "ssl-cert"
        append: yes
  tags: mumble
