---
- hosts: all
  roles:
  - base
  - jnv.unattended-upgrades
  tags: base

- hosts: web
  roles:
  - firewalld
  vars:
    firewall_services:
    - http
    - https
    firewall_ports:
    - 8080/tcp
    - 64738/udp
    - 64738/tcp
  tags: firewall

- hosts: web
  roles:
  - docker
  tags: docker

- hosts: web
  tasks:
    - name: create dump of old postgresql database
      shell: docker exec pretix-postgres pg_dump pretix -U pretix >> /tmp/pretix-dump.sql
      ignore_errors: yes
  tags: pretix

- hosts: web
  roles:
  - traefik
  - docker-compose
  tags:
  - docker
  - compose

- hosts: web
  pre_tasks:
    - name: move old wiki data to new path
      command: mv /var/lib/docker/volumes/root_dokuwiki_data/_data/dokuwiki/data/ {{ dokuwiki_savedir }}
      ignore_errors: yes

    - name: move old wiki users to new path
      command: mv /var/lib/docker/volumes/root_dokuwiki_data/_data/dokuwiki/conf/users.auth.php {{ dokuwiki_base }}/conf/users.auth.php
      ignore_errors: yes
  roles:
  - geerlingguy.nginx
  - geerlingguy.php
  - n0emis.dokuwiki
  tasks:
    - name: Add traefik config
      template:
        src: ../templates/traefik/dokuwiki.yml
        dest: /etc/traefik/dynamic/dokuwiki.yml
  tags: wiki

- hosts: web
  roles:
  - geerlingguy.nginx
  - website
  tasks:
    - name: Add traefik config
      template:
        src: ../templates/traefik/website.yml
        dest: /etc/traefik/dynamic/website.yml
  tags: website

- hosts: web
  tasks:
    - name: create password-user
      user: state=present
            name="pass"

    - name: add user to pass's authorized_keys
      authorized_key: user="pass" manage_dir=true key="{{ item.public_key }}"
                      state=present
      with_items:
      - "{{ users + password_users }}"
      when: item.state != 'absent' and item.public_key is defined and item.public_key != ''

    - name: remove user from pass's authorized_keys
      authorized_key: user="pass" manage_dir=true key="{{ item.public_key }}"
                    state=absent
      with_items:
      - "{{ users + password_users }}"
      when: item.state == 'absent' and item.public_key is defined and item.public_key != ''

- hosts: web
  roles:
    - geerlingguy.postgresql
    - geerlingguy.redis
  tags: pretix

- hosts: web
  pre_tasks:
    - name: restore dump of old postgresql database
      postgresql_db:
        name: "{{ pretix_database_name }}"
        state: restore
        target: "/tmp/pretix-dump.sql"
      ignore_errors: yes
      become_user: postgres

    - name: delete postgresql dump
      file:
        path: "/tmp/pretix-dump.sql"
        state: absent

    - name: create parents for media directory
      file:
        path: "{{ pretix_base_path }}/data"
        recurse: yes
        owner: "pretix"
        group: "pretix"
        state: directory

    - name: move old media directory
      command: mv /var/lib/docker/volumes/root_pretix-data/_data/media {{ pretix_base_path }}/data/
      ignore_errors: yes

    - name: chown new media directory
      file:
        path: "{{ pretix_base_path }}/data/media"
        owner: "pretix"
        group: "pretix"
        recurse: yes
  roles:
    - em0lar.pretix
  tasks:
    - name: Add traefik config
      template:
        src: ../templates/traefik/pretix.yml
        dest: /etc/traefik/dynamic/pretix.yml
  tags: pretix