---
- hosts: all
  roles:
  - base
  tags: base

- hosts: web
  roles:
  - firewalld
  vars:
    firewall_services:
    - http
    - https
    firewall_ports:
    - 8080/tcp
    - 8181/tcp
    - 8008/tcp
    - 8090/tcp
    - 8448/tcp
    - 64738/udp
    - 64738/tcp
  tags: firewall

- hosts: web
  roles:
  - docker
  tags: docker

- hosts: web
  roles:
  - docker-compose
  tags:
  - docker
  - compose
