---
- hosts: all
  roles:
  - base
  - jnv.unattended-upgrades
  tags: base

- hosts: web
  roles:
  - firewalld
  vars:
    firewall_services:
    - http
    - https
    firewall_ports:
    - 8080/tcp
    - 64738/udp
    - 64738/tcp
  tags: firewall

- hosts: web
  roles:
  - docker
  tags: docker

- hosts: web
  roles:
  - traefik
  - docker-compose
  tags:
  - docker
  - compose

- hosts: web
  roles:
  - geerlingguy.nginx
  - geerlingguy.php
  - n0emis.dokuwiki
  tags: wiki

- hosts: web
  tasks:
    - name: create password-user
      user: state=present
            name="pass"

    - name: add user to pass's authorized_keys
      authorized_key: user="pass" manage_dir=true key="{{ item.public_key }}"
                      state=present
      with_items:
      - "{{ users + password_users }}"
      when: item.state != 'absent' and item.public_key is defined and item.public_key != ''

    - name: remove user from pass's authorized_keys
      authorized_key: user="pass" manage_dir=true key="{{ item.public_key }}"
                    state=absent
      with_items:
      - "{{ users + password_users }}"
      when: item.state == 'absent' and item.public_key is defined and item.public_key != ''
